## set the compilation flags. 
if ("${CMAKE_C_COMPILER_ID}"     MATCHES "Cray")
  include(${CMAKE_MODULE_PATH}/cray_c.cmake)
elseif ("${CMAKE_C_COMPILER_ID}" MATCHES "GNU")
  include(${CMAKE_MODULE_PATH}/gnu_c.cmake)
elseif ("${CMAKE_C_COMPILER_ID}" MATCHES "Intel")
  include(${CMAKE_MODULE_PATH}/intel_c.cmake)
elseif ("${CMAKE_C_COMPILER_ID}" MATCHES "PGI")
  include(${CMAKE_MODULE_PATH}/pgi_c.cmake)
elseif ("${CMAKE_C_COMPILER_ID}" MATCHES "MSVC")
 	include(${CMAKE_MODULE_PATH}/msvc_c.cmake)
endif ("${CMAKE_C_COMPILER_ID}"  MATCHES "Cray")

if ("${CMAKE_CXX_COMPILER_ID}"     MATCHES "Cray")
  include(${CMAKE_MODULE_PATH}/cray_cxx.cmake)
elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
  include(${CMAKE_MODULE_PATH}/gnu_cxx.cmake)
elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Intel")
  include(${CMAKE_MODULE_PATH}/intel_cxx.cmake)
elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "PGI")
  include(${CMAKE_MODULE_PATH}/pgi_cxx.cmake)
elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "MSVC")
 	include(${CMAKE_MODULE_PATH}/msvc_cxx.cmake)
endif ("${CMAKE_CXX_COMPILER_ID}"  MATCHES "Cray")

if ("${CMAKE_Fortran_COMPILER_ID}"     MATCHES "Cray")
  	include(${CMAKE_MODULE_PATH}/cray_fortran.cmake)
elseif ("${CMAKE_Fortran_COMPILER_ID}" MATCHES "GNU")
	include(${CMAKE_MODULE_PATH}/gnu_fortran.cmake)
elseif ("${CMAKE_Fortran_COMPILER_ID}" MATCHES "Intel")
  	include(${CMAKE_MODULE_PATH}/intel_fortran.cmake)
elseif ("${CMAKE_Fortran_COMPILER_ID}" MATCHES "PGI")
    	include(${CMAKE_MODULE_PATH}/pgi_fortran.cmake)
elseif ("${CMAKE_Fortran_COMPILER_ID}" MATCHES "MSVC")
  	include(${CMAKE_MODULE_PATH}/msvc_fortran.cmake)
endif ("${CMAKE_Fortran_COMPILER_ID}"  MATCHES "Cray")
